<a href="https://colab.research.google.com/github/st3vejobs/SQLBridgeHW1/blob/main/Bridge_Homework_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Shane Hylton Bridge HW 2



#Question 1


In [106]:
import numpy as np
from sympy import Poly, Symbol, solve_poly_inequality, solve, sin, sympify
import sympy as sp

sq_array = np.matrix('25 7; 7 25')
identity = np.matrix('1 0; 0 1')

sq_a = sq_array[0]
sq_b = sq_array[1]

a = identity[0]
b = identity[1]

lam = Symbol('lam')
exp = sympify(lam*a)
expa = sympify(lam*b)

exp1 = sympify(sq_array[0,0] - exp[0,0])
exp2 = sympify(sq_array[0,1] - exp[0,1])
exp3 = sympify(sq_array[1,0] - expa[0,0])
exp4 = sympify(sq_array[1,1] - expa[0,1])

f1 = exp1*exp4
f2 = exp2*exp3

func = sympify(f1-f2)

print(f'The two possible eigenvalues are: {solve(func, lam)}')

#Now need to find the eigenvectors

eigval = solve(func, lam)

exp1 = sympify(sq_array[0,0] - eigval[0])
exp2 = sympify(sq_array[0,1] - exp[0,1])
exp3 = sympify(sq_array[1,0] - expa[0,0])
exp4 = sympify(sq_array[1,1] - eigval[0])

x = Symbol('x')
y = Symbol('y')
rat = Symbol('rat') #rat will be ratio of y/x

v1 = sympify(exp1*x + exp2*y)
v1 = sympify(exp1 + exp2*rat)
v2 = sympify(exp3*x + exp4*y)
v2 = sympify(exp3 + exp4*rat)

rat1 = float(solve(v1, rat)[0]) #converting the list's single element to a float

exp1 = sympify(sq_array[0,0] - eigval[1])
exp2 = sympify(sq_array[0,1] - exp[0,1])
exp3 = sympify(sq_array[1,0] - expa[0,0])
exp4 = sympify(sq_array[1,1] - eigval[1])

v1 = sympify(exp1*x + exp2*y)
v1 = sympify(exp1 + exp2*rat)
v2 = sympify(exp3*x + exp4*y)
v2 = sympify(exp3 + exp4*rat)

rat2 = float(solve(v1,rat)[0])

vec1 = ([1],[rat1])
vec2 = ([1], [rat2])


print(f'The eigenvectors for this matrix are:')
print(np.matrix(vec1))
print(np.matrix(vec2))
print('The ratio of the x and y eigenvalues is the same as it is in the numpy method.')
print('Using the built in function: ')
print(np.linalg.eig(sq_array))








The two possible eigenvalues are: [18, 32]
The eigenvectors for this matrix are:
[[1.0000]
 [-1.0000]]
[[1.0000]
 [1.0000]]
The ratio of the x and y eigenvalues is the same as it is in the numpy method.
Using the built in function: 
(array([32.0000, 18.0000]), matrix([[0.7071, -0.7071],
        [0.7071, 0.7071]]))


#Question 2


In [119]:
import numpy as np
from scipy.linalg import orth
np.set_printoptions(formatter ={'float':"{:.4f}".format})
Mat = np.matrix('4 4; -3 3')
MatT = np.transpose(Mat)

U = Mat*MatT
W = MatT*Mat

eigVw, eigW = np.linalg.eig(W)
eigVu, eigU = np.linalg.eig(U)
W = W.astype(float)
U = U.astype(float)
eigU = np.transpose(eigU)
eigW = np.transpose(eigW) #numpy stores the eigenvectors as columns

Vt = eigW
Ut = eigU

a = eigVw[0]**(1/2)
b = eigVw[1]**(1/2)
c = 0
S = np.matrix([[a,c],[c,b]])

SVD = Ut*S*Vt
print('The Singular Value Decomposition is given by: ')
print(f'{SVD} = {Ut} * {S} * {Vt}')

#Using numpy function:
U, s, V = np.linalg.svd(Mat)



The Singular Value Decomposition is given by: 
[[4.0000 4.0000]
 [-3.0000 3.0000]] = [[1.0000 0.0000]
 [0.0000 1.0000]] * [[5.6569 0.0000]
 [0.0000 4.2426]] * [[0.7071 0.7071]
 [-0.7071 0.7071]]


# Question 3


In [121]:
import numpy as np

#For 2x2 arrays:
arr = np.matrix('3 8; 4 6')
detarr = arr[0,0]*arr[1,1] - arr[0,1]*arr[1,0]
print(detarr)

#For 3x3 arrays:
arr3 = np.matrix('3 8 10; 3 6 7; 7 2 2')

det3 = 0
for num in range(0,3):
  if num == 0:
    det3 += arr3[0,0]*(arr3[1,1]*arr3[2,2] - arr3[1,2]*arr3[2,1])
  elif num == 1:
    det3 -= arr3[0,1]*(arr3[1,0]*arr3[2,2] - arr3[1,2]*arr3[2,0])
  elif num == 2:
    det3 += arr3[0,2]*(arr3[1,0]*arr3[2,1] - arr3[1,1]*arr3[2,0])
print(det3)


-14
-22
